# ============================================================
# Setup grid box config untuk 4 protein target
# Binding site coordinates dari literatur / co-crystal ligand
# ============================================================

import os

os.makedirs("config", exist_ok=True)

# Grid box per protein — center dari binding pocket
# Source: PDB co-crystal ligand centroid / published docking studies
configs = {
    "2AM9": {   # AR — Androgen Receptor
        "name"  : "Androgen Receptor (AR)",
        "cx": 2.516, "cy": 27.783, "cz": 3.995,
        "sx": 20,    "sy": 20,    "sz": 20,
        "ref"   : "PDB 2AM9, ligand R1881 binding pocket"
    },
    "3ERT": {   # ESR1 — Estrogen Receptor alpha
        "name"  : "Estrogen Receptor alpha (ESR1)",
        "cx": -1.800, "cy": 3.900, "cz": 14.800,
        "sx": 22,     "sy": 22,   "sz": 22,
        "ref"   : "PDB 3ERT, 4-OH-tamoxifen binding pocket"
    },
    "3HQR": {   # HIF-1alpha
        "name"  : "HIF-1alpha (HIF1A)",
        "cx": -8.200, "cy": 18.500, "cz": -2.100,
        "sx": 20,     "sy": 20,    "sz": 20,
        "ref"   : "PDB 3HQR, PHD2-HIF1A peptide interface"
    },
    "1SVC": {   # NF-kB1
        "name"  : "NF-kB1 (NFKB1)",
        "cx": 32.480, "cy": 45.510, "cz": 57.330,
        "sx": 22,     "sy": 22,    "sz": 22,
        "ref"   : "PDB 1SVC, DNA binding domain active site"
    },
}

for pdb_id, cfg in configs.items():
    conf = f"""# Docking config: {cfg['name']}
# Grid box reference: {cfg['ref']}
# Generated by setup_docking.py

receptor = protein/{pdb_id}.pdbqt

center_x = {cfg['cx']}
center_y = {cfg['cy']}
center_z = {cfg['cz']}

size_x = {cfg['sx']}
size_y = {cfg['sy']}
size_z = {cfg['sz']}

exhaustiveness = 16
num_modes       = 9
energy_range    = 3
"""
    fname = f"config/config_{pdb_id}.txt"
    with open(fname, "w") as f:
        f.write(conf)
    print(f"Saved: {fname}  ({cfg['name']})")

print("\nGrid box summary:")
print(f"{'Protein':<10} {'Center (x,y,z)':<30} {'Size':<12} {'Reference'}")
print("-"*90)
for pdb_id, cfg in configs.items():
    print(f"{pdb_id:<10} ({cfg['cx']:>7.2f},{cfg['cy']:>7.2f},{cfg['cz']:>7.2f})  "
          f"{'20x20x20':<12} {cfg['ref']}")
